#version: '3.1'
services:
  application:
    build: ./docker
    image: leafphp/docker
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      # For SQlite database, mount dir from host OS
      - type: bind
        source: /var/local/wos245/
        target: /var/www/wos245/
  db-migration:
    image: leafphp/docker
    depends_on:
      - application
    restart: "no"
    entrypoint: ["bash", "-c", "php leaf db:migrate -vvv"]
